# Generated by Django 4.2.7 on 2024-02-06 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
