# Generated by Django 4.2.7 on 2024-02-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_order_products_alter_order_status_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', to='shop.product', verbose_name='Продукты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False, editable=False, verbose_name='Статус закза'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
