# Generated by Django 4.2.7 on 2024-02-07 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_total_price_order_total_price_per_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price_per_item',
        ),
    ]
