# Generated by Django 4.2.7 on 2024-02-07 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_order_total_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='Пользователь')),
                ('products', models.TextField(verbose_name='Список продуктов и количество')),
                ('purchase_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата покупки')),
            ],
        ),
    ]
