# Generated by Django 4.2.7 on 2024-02-08 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_purchasereport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasereport',
            options={'verbose_name': 'Отчет по покупкам', 'verbose_name_plural': 'Отчеты по покупкам'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория'),
        ),
    ]
